version: '3.8'

services:
  webapp:
    environment:
      - APP_DEBUG=true
      - APP_ENV=dev

    volumes:
      - ./webapp:/var/www/labyrinth

  proxy:
    volumes:
      - ./logs/nginx:/var/log/nginx
