version: '3.8'

services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"

  api-domain:
    build:
      dockerfile: ./domain/api/Dockerfile
    ports:
      - "127.0.0.1:9001:80"

  webapp:
    build:
      dockerfile: ./webapp/Dockerfile
    environment:
      - APP_DEBUG=true
      - APP_ENV=dev

    volumes:
      - ./webapp/src:/var/www/labyrinth/src
      - ./webapp/templates:/var/www/labyrinth/templates

  mercure:
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev

  webapp-migrations:
    build:
      dockerfile: ./webapp/migrations/Dockerfile
    environment:
      - APP_DEBUG=true
      - APP_ENV=dev

  proxy:
    build:
      dockerfile: ./proxy/Dockerfile
    volumes:
      - ./webapp/public/images:/var/www/labyrinth/public/images
      - ./webapp/public/styles:/var/www/labyrinth/public/styles
    ports:
      - "127.0.0.1:9000:80"
