version: '3.8'

services:
  api-domain:
    image: jonathanmarmelab/labyrinth-domain-api:latest

  webapp:
    image: jonathanmarmelab/labyrinth-webapp:latest
    environment:
      - APP_DEBUG=false
      - APP_ENV=prod

  webapp-migrations:
    image: jonathanmarmelab/labyrinth-webapp-migrations:latest
    environment:
      - APP_DEBUG=false
      - APP_ENV=prod

  proxy:
    image: jonathanmarmelab/labyrinth-proxy:latest
    volumes:
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
